persiancal/cal-events

- cmd/thetool/validate.go
- cmd/thetool/validate_test.go
- dist/jalali.json
- dist/jalali.yml
- jalali/04-tir.yml
- jalali/06-shahrivar.yml
> add partial-key validator

- jalali/01-farvardin.yml
> edit partial keys and add some links from wikipedia in farvardin. (Issue #13)

- hijri/01-muharram.yml
fixes #66 Add events of Muharram
> Add events of Muharram. closes #66

- cmd/thetool/links.go
- cmd/thetool/links_test.go
> add test for validating if test links works

- hijri/02-safar.yml
Edit Safar reference https://fa.wikipedia.org/wiki/صفر_(ماه)
> Edit Safar

- jalali/01-farvardin.yml
- jalali/02-ordibehesht.yml
- jalali/03-khordad.yml
I've edited some partial keys that have arabic alef and lam or have a conflict in its English names in accordance with English names in Wikipedia.
> edit some partial keys with arabic alef and lam

- hijri/12-zulhijjah.yml
من طبق ویکپدیا سعی کردم مناسبت‌هایی که توی تقویم ایران به رسمیت شمرده میشه رو وارد کنم.
اگر مشکلی بود بنظرت بگو که درستش کنم.
> مناسبت‌های ذیحجه

- hijri/06-jumada_al-akhirah.yml
> Update Jumada-al-akhirah events

- hijri/02-safar.yml
- hijri/03-rabi_al-awwal.yml
- hijri/04-rabi_al-thani.yml
- hijri/05-jumada_al-ula.yml
- hijri/06-jumada_al-akhirah.yml
- hijri/07-rajab.yml
In order to regard better alignment between partial keys, Some partial keys have been edited.
> Some partial keys have been edited

- jalali/09-azar.yml
سلام
برای من هم مقدور نبود که
make generate 
رو اجرا کنم
تشکر
> Fixed the ninth month of jalali calendar(Azar).Issue#21

- hijri/09-ramadan.yml
نسخه اول رمضان آماده شد
اگر مشکلی داشت بگین که تصحیح شه
> Ramadan (issue #74)

- cmd/thetool/validate.go
- cmd/thetool/validate_test.go
> add validator for calendar key

- gregorian/02-february.yml
> Added events of February

- gregorian/10-october.yml
with wikipedia link from https://www.un.org/en/sections/observances/international-days/
> Add october events 

- gregorian/08-august.yml
with wikipedia link from https://www.un.org/en/sections/observances/international-days/
> Add august events

- cmd/thetool/generate.go
- cmd/thetool/web_gen.go
> POC: generate markdown

- gregorian/11-november.yml
> Update November events

- gregorian/10-october.yml
Add `world standards day` to `14 October`.
https://en.wikipedia.org/wiki/World_Standards_Day
> add world standards day to 14 October

- cmd/thetool/api.go
- cmd/thetool/generate.go
the only implemented api is the daily one. the idea is to generate
**all possible combination** (even empty ones) of a query (no search/no range)
the API is only for GET, no other method or query parameter is supported
This PR only contain daily events.
> stub for static api

- gregorian/07-july.yml
> Add July month events. closes #136

- gregorian/01-january.yml
> Edit january

- gregorian/06-june.yml
Data of the first half of June was written.
Reference to #135.
> Data entry for June
